@base_uri=http://localhost:3333/api
@version=HTTP/1.1

# Login/Signup
POST http://localhost:3333/api/auth/login
Content-Type: application/json

{
    "email": "damareshwarakumar@gmail.com",
    "password": "password"
}